### ISSUE TITLE
Feature request: Suggest @deathdate rule when encountering `// TODO: Delete ...` comments

### ISSUE THREAD

**Issue by broofa** [betaorbust/eslint-plugin-pocket-fluff#1]
@chrisgilmerproj pointed me at your @deathdate rule.  Very cool!

My one nit/comment is that the dead code use case is (for me) rare enough that I'd have to look up the @deathdate notation each time I wanted to use it (or, more likely, just take a guess, get it wrong, and have my comment quietly fail to trigger the desired warning.)

What I currently do for code like this is add a comment to the effect of, `// TODO: Delete <blah blah>`.  Picking up on that sort of comment and suggesting (or even `--fix`ing?) a @deathdate rule when encountering such a comment would be a nice feature.

**Comment by betaorbust** [comment]
Oh, that would be great! I think maybe it can be a separate rule, so it can be optionally applied.
I've been considering making an @todo annotation that would have the same format, but different connotation -- like "fix this by this date" instead of "kill this by this date"

**Comment by broofa** [comment]
See also https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/expiring-todo-comments.md
